function stdv_t = stdv_norm_truncated(mean,stdv,xmin,xmax)

mean_t = mean_norm_truncated(mean,stdv,xmin,xmax);

var_t = 1/(ferum_cdf(1,(xmax-mean)/stdv,0,1)-ferum_cdf(1,(xmin-mean)/stdv,0,1)) * ...
           ( mean^2 * (ferum_cdf(1,(xmax-mean)/stdv,0,1)-ferum_cdf(1,(xmin-mean)/stdv,0,1)) - ...
             2*mean*stdv * (ferum_pdf(1,(xmax-mean)/stdv,0,1)-ferum_pdf(1,(xmin-mean)/stdv,0,1)) - ...
             stdv^2 * ((xmax-mean)/stdv*ferum_pdf(1,(xmax-mean)/stdv,0,1)-(xmin-mean)/stdv*ferum_pdf(1,(xmin-mean)/stdv,0,1)) + ...
             stdv^2 * (ferum_cdf(1,(xmax-mean)/stdv,0,1)-ferum_cdf(1,(xmin-mean)/stdv,0,1)) ) - ...
        mean_t^2;

stdv_t = var_t^0.5;